### ISSUE TITLE
use smplx add-on

### ISSUE THREAD

**Issue by yinkangning0124** [GuyTevet/MotionCLIP#24]
Hi MotionCLIP team,
    Thanks for your great work, here I am wondering how to render a single image using the blender and the smplx add-on. In my work, I wanna render images from the HumanML3D format motion. Could you give me some instructions?
    Really appreciate your work again and hope hearing from you!

Kangning

**Comment by yinkangning0124** [comment]
By the way, is there any automatic python scripts to process HumanML3D motion into rendered images?

**Comment by GuyTevet** [comment]
I don't know of any such script, but since HumanML3D is originally generated from amass files, you can use the amass files and load them to the Blender SMPLX add-on. In our case, we just rendered the images with this add-on, a plain white background, and the default clothed skin provided with the add-on

**Comment by Kebii** [comment]
Hi, I'm also interested in rendering images from the HumanML3D dataset. Have you solved this problem?

**Comment by 177-Liukuan** [comment]
> Hi, I'm also interested in rendering images from the HumanML3D dataset. Have you solved this problem?您好，我也对渲染 HumanML3D 数据集中的图像很感兴趣。您解决这个问题了吗？

me too,have you solved this problem?
