### ISSUE TITLE
"action2motion_joints" list & AMASS db file does not include translation vector

### ISSUE THREAD

**Issue by MenelauseZzw** [GuyTevet/MotionCLIP#4]
Thanks for the interesting work!
I have two questions regarding amass.py and dataset.py respectively.

In line 93-95 in amass.py, why you only select such 18 joints (should it still be 24 or 22?) and switch #8 joint to the root position?

In line 115-122 in dataset.py, should the translation be the "trans" vector where "trans" is the key word of AMASS data dictionary? It seems that you did not store this "trans" vector into any places. Or do I misunderstand the meaning of "self.translation"?

Thanks!

**Comment by GuyTevet** [comment]
Hi Zhongwen,
https://github.com/GuyTevet/MotionCLIP/blob/c2b9f40b0e721e42981f3e8b58133a1c51fde715/src/datasets/amass.py#L95
(1) This is a legacy code not in use. The real joints in use are parsed here:

https://github.com/GuyTevet/MotionCLIP/blob/c2b9f40b0e721e42981f3e8b58133a1c51fde715/src/datasets/amass_parser.py#L40

(2) Those lines of code are not in use since we use only `rot6d` pose representation.
